export const messages = {
  id: {
    dateLocale: "id-ID",
    nativeValidationTitle: "Validasi kriptografi native",
    nativeValidationRunning: "Menjalankan vektor publik…",
    nativeValidationPassed: "LULUS",
    nativeValidationFailed: "GAGAL",
    nativeValidationDescription: "Argon2id 64 MiB · acak aman AES-256-GCM · hanya data publik sintetis",
    appName: "rhasia-scret",
    eyebrow: "Aplikasi seluler",
    title: "Autentikator tanpa pengetahuan",
    description:
      "Masuk atau buat akun untuk mengakses Vault terenkripsi Anda. Rahasia dan OTP tetap hanya di perangkat ini.",
    emailLabel: "Alamat email",
    emailPlaceholder: "nama@contoh.com",
    emailRequired: "Masukkan alamat email.",
    emailInvalid: "Masukkan alamat email yang valid.",
    sendLink: "Lanjutkan dengan email",
    sendingLink: "Mengirim tautan…",
    linkSent:
      "Periksa email Anda dan buka tautan masuk di perangkat ini. Akun hosted baru tersedia setelah email diverifikasi.",
    signInFailed: "Tautan email tidak dapat dikirim. Coba lagi.",
    callbackFailed: "Tautan masuk tidak dapat diverifikasi.",
    signedIn: "Sesi seluler terlindungi aktif.",
    verifyingSession: "Memverifikasi akses aplikasi…",
    inactiveSession: "Akun ini belum memiliki akses aktif ke aplikasi.",
    sessionUnavailable: "Sesi tidak dapat diverifikasi. Periksa koneksi lalu coba lagi.",
    signedInAs: "Masuk sebagai",
    signOut: "Keluar",
    language: "Bahasa",
    switchLanguage: "Gunakan English",
    configurationError: "Konfigurasi aplikasi seluler belum lengkap.",
    openShareLink: "Tautan berbagi aman siap dibuka setelah Vault tidak terkunci.",
    securityNote: "Token sesi disimpan di Keychain atau Android Keystore dan tidak pernah dicatat ke log.",
    personalVaultLoading: "Memuat Brankas Pribadi…",
    personalVaultLoadError: "Brankas Pribadi tidak dapat dimuat.",
    retry: "Coba lagi",
    personalVaultReady: "Brankas Pribadi siap",
    personalVaultUnlockDescription: "Masukkan Passphrase Brankas untuk membuka kunci sepenuhnya di perangkat ini.",
    personalVaultOfflineUnlockDescription:
      "Server tidak tersedia. Masukkan Passphrase Brankas untuk membuka snapshot terenkripsi hanya-baca di perangkat ini; perubahan tidak akan diantrekan atau diputar ulang.",
    unlockVault: "Buka kunci Brankas",
    personalVaultUnlocking: "Membuka kunci…",
    personalVaultUnlockError: "Brankas tidak dapat dibuka. Periksa Passphrase Brankas dan coba lagi.",
    personalVaultUnlocked: "Brankas Pribadi tidak terkunci",
    personalVaultUnlockedDescription: "Kunci hanya disimpan di memori dan dibersihkan saat aplikasi tidak aktif.",
    secureShareLinkRedeemed: "Secure Share Link satu-kali berhasil ditebus dan Brankas Bersama ditambahkan.",
    secureShareLinkRefreshError:
      "Secure Share Link berhasil ditebus, tetapi daftar Brankas belum dapat diperbarui. Buka ulang saat daring; tautan tidak dapat digunakan lagi.",
    secureShareLinkError:
      "Secure Share Link tidak dapat ditebus. Tautan mungkin tidak valid, kedaluwarsa, atau telah digunakan.",
    lockVault: "Kunci Brankas",
    authenticatorAccounts: "Akun Authenticator",
    authenticatorAccountImportGuidance:
      "Tempel URI otpauth dari sumber tepercaya. URI dan rahasia diproses hanya di perangkat dan hanya muatan terenkripsi yang dikirim.",
    authenticatorAccountUri: "URI otpauth",
    destinationVault: "Brankas tujuan",
    sharedVault: "Brankas Bersama",
    sharedVaults: "Brankas Bersama",
    sharedVaultOwner: "Pemilik",
    sharedVaultViewer: "Anggota",
    permissionAdd: "Tambah akun",
    permissionEdit: "Ubah akun",
    permissionDelete: "Hapus akun",
    permissionReadOnly: "Hanya baca",
    createSecureShareLink: "Undang dengan Secure Share Link",
    recipientEmail: "Email penerima",
    recipientEmailInvalid: "Masukkan email penerima yang valid.",
    createAndShareLink: "Buat dan bagikan tautan",
    creatingSecureShareLink: "Membuat tautan…",
    secureShareLinkCreated:
      "Secure Share Link dibuat dan dibuka di lembar berbagi perangkat. Tautan hanya dapat digunakan satu kali.",
    secureShareLinkCreateError: "Secure Share Link tidak dapat dibuat. Periksa penerima, izin, dan koneksi.",
    loadAuditHistory: "Muat riwayat audit",
    auditHistoryError: "Riwayat audit tidak dapat dimuat.",
    auditAccountAccessed: "Akun diakses",
    auditAccountAdded: "Akun ditambahkan",
    auditAccountUpdated: "Akun diubah",
    auditAccountDeleted: "Akun dihapus",
    auditMemberRevoked: "Akses anggota dicabut",
    auditArchiveImported: "Arsip diimpor",
    auditSecurityActivity: "Aktivitas keamanan Brankas",
    manageMemberPermissions: "Kelola izin anggota",
    memberPermissionDefaults: "Izin bawaan anggota",
    allowed: "Diizinkan",
    notAllowed: "Tidak diizinkan",
    savePermissions: "Simpan izin",
    memberPermissionsError: "Izin anggota tidak dapat dimuat atau disimpan. Muat ulang sebelum mencoba lagi.",
    personalVault: "Brankas Pribadi",
    authenticatorAccountUriInvalid: "Masukkan URI otpauth yang valid.",
    authenticatorAccountImport: "Impor Akun Authenticator",
    authenticatorAccountSaving: "Menyimpan muatan terenkripsi…",
    authenticatorAccountImportError: "Akun tidak dapat diimpor. Periksa URI dan izin Brankas.",
    authenticatorAccountRefreshError:
      "Akun tersimpan, tetapi snapshot terenkripsi belum dapat diperbarui. Buka ulang Brankas saat daring.",
    generateCode: "Buat kode offline",
    copyCode: "Salin kode",
    codeCopied: "Kode disalin ke papan klip perangkat.",
    deleteAccount: "Hapus akun",
    deletingAccount: "Menghapus…",
    deleteAccountError: "Akun tidak dapat dihapus. Data mungkin telah berubah; muat ulang Brankas.",
    offlineSnapshotReadOnly:
      "Snapshot offline bersifat hanya-baca. Pembuatan kode dan penyalinan tetap lokal; perubahan dinonaktifkan dan tidak akan diantrekan.",
    scanQrCode: "Pindai kode QR",
    scanAuthenticatorQr: "Pindai QR Authenticator",
    qrScanClientOnly: "Data QR diproses hanya di perangkat dan tidak pernah dikirim sebagai teks biasa.",
    cameraPreview: "Pratinjau kamera pemindai QR",
    cameraPermissionChecking: "Memeriksa izin kamera…",
    cameraPermissionGuidance: "Izin kamera diperlukan hanya saat Anda memilih untuk memindai kode QR Authenticator.",
    allowCamera: "Izinkan kamera",
    cancelQrScan: "Batalkan pemindaian",
    archiveTitle: "Arsip Brankas terenkripsi",
    archiveGuidance: "Ekspor atau impor arsip terenkripsi melalui pemilih dokumen dan lembar berbagi perangkat.",
    archiveExportVault: "Brankas milik Anda untuk diekspor",
    archiveImportDestination: "Brankas tujuan impor",
    prepareArchive: "Siapkan arsip terenkripsi",
    archiveSeparateKeyWarning: "Simpan kunci arsip terpisah dari berkas dan bagikan melalui saluran berbeda.",
    copyArchiveKey: "Salin kunci arsip",
    shareEncryptedArchive: "Bagikan berkas arsip terenkripsi",
    archiveKey: "Kunci arsip",
    archiveKeyInvalid: "Masukkan kunci arsip Base64 32-byte.",
    chooseArchive: "Pilih dan buka arsip",
    archivePreview: "Arsip {vault} berisi {count} akun. Impor dapat menyertakan duplikat.",
    importArchive: "Impor akun terenkripsi",
    archiveKeyCopied: "Kunci arsip disalin.",
    archiveImportSuccess: "Arsip berhasil diimpor dan snapshot diperbarui.",
    archiveImportedRefreshError:
      "Arsip berhasil diimpor, tetapi snapshot belum dapat diperbarui. Buka ulang Brankas saat daring; jangan impor berkas lagi.",
    archiveError: "Operasi arsip gagal. Periksa berkas, kunci, koneksi, dan izin Brankas.",
    personalVaultSetupTitle: "Amankan Brankas Pribadi",
    personalVaultSetupDescription:
      "Nama dan konfigurasi Brankas dienkripsi di perangkat ini sebelum dikirim ke server.",
    personalVaultDefaultName: "Brankas Pribadi",
    vaultName: "Nama Brankas",
    vaultNameRequired: "Masukkan Nama Brankas.",
    vaultPassphrase: "Passphrase Brankas",
    passphraseInvalid: "Passphrase Brankas harus berisi setidaknya tiga karakter.",
    confirmVaultPassphrase: "Masukkan ulang Passphrase Brankas",
    passphraseMismatch: "Passphrase Brankas tidak cocok.",
    passphraseAcknowledgement: "Saya telah menyimpan Passphrase Brankas di tempat yang aman.",
    passphraseAcknowledgementRequired: "Konfirmasikan bahwa Passphrase Brankas telah disimpan.",
    passphraseRecoveryWarning:
      "Tanpa Pemulihan Berbantuan Passkey yang telah didaftarkan, Passphrase Brankas yang hilang tidak dapat dipulihkan.",
    personalVaultCreate: "Amankan Brankas Pribadi",
    personalVaultCreating: "Membuat kunci dan mengenkripsi…",
    personalVaultSetupError: "Brankas Pribadi tidak dapat diamankan. Data sensitif tidak dikirim sebagai teks biasa.",
  },
  en: {
    dateLocale: "en-US",
    nativeValidationTitle: "Native cryptography validation",
    nativeValidationRunning: "Running public vectors…",
    nativeValidationPassed: "PASSED",
    nativeValidationFailed: "FAILED",
    nativeValidationDescription: "Argon2id 64 MiB · AES-256-GCM secure random · synthetic public data only",
    appName: "rhasia-scret",
    eyebrow: "Mobile application",
    title: "Zero-knowledge authenticator",
    description:
      "Sign in or create an account to access your encrypted Vaults. Secrets and OTPs remain only on this device.",
    emailLabel: "Email address",
    emailPlaceholder: "name@example.com",
    emailRequired: "Enter an email address.",
    emailInvalid: "Enter a valid email address.",
    sendLink: "Continue with email",
    sendingLink: "Sending link…",
    linkSent:
      "Check your email and open the sign-in link on this device. A new hosted account becomes available after email verification.",
    signInFailed: "The email link could not be sent. Try again.",
    callbackFailed: "The sign-in link could not be verified.",
    signedIn: "Protected mobile session active.",
    verifyingSession: "Verifying application access…",
    inactiveSession: "This account does not have active application access.",
    sessionUnavailable: "The session could not be verified. Check the connection and try again.",
    signedInAs: "Signed in as",
    signOut: "Sign out",
    language: "Language",
    switchLanguage: "Gunakan Bahasa Indonesia",
    configurationError: "Mobile application configuration is incomplete.",
    openShareLink: "The Secure Share Link is ready to open after the Vault is unlocked.",
    securityNote: "Session tokens are stored in Keychain or Android Keystore and are never written to logs.",
    personalVaultLoading: "Loading Personal Vault…",
    personalVaultLoadError: "The Personal Vault could not be loaded.",
    retry: "Try again",
    personalVaultReady: "Personal Vault ready",
    personalVaultUnlockDescription: "Enter the Vault Passphrase to unlock entirely on this device.",
    personalVaultOfflineUnlockDescription:
      "The server is unavailable. Enter the Vault Passphrase to open this device's read-only encrypted snapshot; mutations will not be queued or replayed.",
    unlockVault: "Unlock Vault",
    personalVaultUnlocking: "Unlocking…",
    personalVaultUnlockError: "The Vault could not be unlocked. Check the Vault Passphrase and try again.",
    personalVaultUnlocked: "Personal Vault unlocked",
    personalVaultUnlockedDescription: "Keys are retained only in memory and cleared whenever the app becomes inactive.",
    secureShareLinkRedeemed: "The one-time Secure Share Link was redeemed and the Shared Vault was added.",
    secureShareLinkRefreshError:
      "The Secure Share Link was redeemed, but the Vault list could not refresh. Reopen while online; the link cannot be used again.",
    secureShareLinkError: "The Secure Share Link could not be redeemed. It may be invalid, expired, or already used.",
    lockVault: "Lock Vault",
    authenticatorAccounts: "Authenticator Accounts",
    authenticatorAccountImportGuidance:
      "Paste an otpauth URI from a trusted source. The URI and secret are processed only on this device; only encrypted payload is sent.",
    authenticatorAccountUri: "otpauth URI",
    destinationVault: "Destination Vault",
    sharedVault: "Shared Vault",
    sharedVaults: "Shared Vaults",
    sharedVaultOwner: "Owner",
    sharedVaultViewer: "Member",
    permissionAdd: "Add accounts",
    permissionEdit: "Edit accounts",
    permissionDelete: "Delete accounts",
    permissionReadOnly: "Read only",
    createSecureShareLink: "Invite with a Secure Share Link",
    recipientEmail: "Recipient email",
    recipientEmailInvalid: "Enter a valid recipient email.",
    createAndShareLink: "Create and share link",
    creatingSecureShareLink: "Creating link…",
    secureShareLinkCreated:
      "The Secure Share Link was created and opened in the device share sheet. It can be used only once.",
    secureShareLinkCreateError:
      "The Secure Share Link could not be created. Check the recipient, permissions, and connection.",
    loadAuditHistory: "Load audit history",
    auditHistoryError: "Audit history could not be loaded.",
    auditAccountAccessed: "Account accessed",
    auditAccountAdded: "Account added",
    auditAccountUpdated: "Account updated",
    auditAccountDeleted: "Account deleted",
    auditMemberRevoked: "Member access revoked",
    auditArchiveImported: "Archive imported",
    auditSecurityActivity: "Vault security activity",
    manageMemberPermissions: "Manage member permissions",
    memberPermissionDefaults: "Default member permissions",
    allowed: "Allowed",
    notAllowed: "Not allowed",
    savePermissions: "Save permissions",
    memberPermissionsError: "Member permissions could not be loaded or saved. Refresh before trying again.",
    personalVault: "Personal Vault",
    authenticatorAccountUriInvalid: "Enter a valid otpauth URI.",
    authenticatorAccountImport: "Import Authenticator Account",
    authenticatorAccountSaving: "Saving encrypted payload…",
    authenticatorAccountImportError: "The account could not be imported. Check the URI and Vault permissions.",
    authenticatorAccountRefreshError:
      "The account was saved, but the encrypted snapshot could not be refreshed. Reopen the Vault while online.",
    generateCode: "Generate offline code",
    copyCode: "Copy code",
    codeCopied: "Code copied to the device clipboard.",
    deleteAccount: "Delete account",
    deletingAccount: "Deleting…",
    deleteAccountError: "The account could not be deleted. It may have changed; refresh the Vault.",
    offlineSnapshotReadOnly:
      "The offline snapshot is read-only. Code generation and copying remain local; mutations are disabled and will not be queued.",
    scanQrCode: "Scan QR code",
    scanAuthenticatorQr: "Scan Authenticator QR",
    qrScanClientOnly: "QR data is processed only on this device and is never sent as plaintext.",
    cameraPreview: "QR scanner camera preview",
    cameraPermissionChecking: "Checking camera permission…",
    cameraPermissionGuidance: "Camera permission is needed only when you choose to scan an Authenticator QR code.",
    allowCamera: "Allow camera",
    cancelQrScan: "Cancel scanning",
    archiveTitle: "Encrypted Vault archive",
    archiveGuidance: "Export or import encrypted archives through the device document picker and share sheet.",
    archiveExportVault: "Owned Vault to export",
    archiveImportDestination: "Import destination Vault",
    prepareArchive: "Prepare encrypted archive",
    archiveSeparateKeyWarning: "Keep the archive key separate from the file and share it through a different channel.",
    copyArchiveKey: "Copy archive key",
    shareEncryptedArchive: "Share encrypted archive file",
    archiveKey: "Archive key",
    archiveKeyInvalid: "Enter a 32-byte Base64 archive key.",
    chooseArchive: "Choose and open archive",
    archivePreview: "The {vault} archive contains {count} accounts. Import may include duplicates.",
    importArchive: "Import encrypted accounts",
    archiveKeyCopied: "Archive key copied.",
    archiveImportSuccess: "Archive imported and the snapshot refreshed.",
    archiveImportedRefreshError:
      "The archive was imported, but the snapshot could not refresh. Reopen the Vault while online; do not import the file again.",
    archiveError: "The archive operation failed. Check the file, key, connection, and Vault permissions.",
    personalVaultSetupTitle: "Secure your Personal Vault",
    personalVaultSetupDescription:
      "The Vault Name and configuration are encrypted on this device before anything is sent to the server.",
    personalVaultDefaultName: "Personal Vault",
    vaultName: "Vault Name",
    vaultNameRequired: "Enter a Vault Name.",
    vaultPassphrase: "Vault Passphrase",
    passphraseInvalid: "The Vault Passphrase must contain at least three characters.",
    confirmVaultPassphrase: "Re-enter Vault Passphrase",
    passphraseMismatch: "The Vault Passphrases do not match.",
    passphraseAcknowledgement: "I saved the Vault Passphrase in a safe place.",
    passphraseAcknowledgementRequired: "Confirm that the Vault Passphrase has been saved.",
    passphraseRecoveryWarning:
      "Without previously enrolled Passkey-Assisted Recovery, a lost Vault Passphrase cannot be recovered.",
    personalVaultCreate: "Secure Personal Vault",
    personalVaultCreating: "Creating keys and encrypting…",
    personalVaultSetupError: "The Personal Vault could not be secured. Sensitive data was not sent as plaintext.",
  },
} as const;

export type MobileLocale = keyof typeof messages;
export type MobileMessages = { [Key in keyof typeof messages.id]: string };

export function translate(locale: MobileLocale): MobileMessages {
  return messages[locale];
}
