allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
