overrides:
  '@hono/node-server': 2.0.12
  find-my-way: 9.7.0
  postcss: 8.5.23
  sharp: 0.35.3
  valibot: 1.4.2

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
