import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

export const PROJECT_PREFIX = "rhasia-load-";

export const PROJECT_PATTERN = /^rhasia-load-[0-9a-f]{12,32}$/;

export const WEB_ORIGIN = "http://localhost:4000";

export const MAILPIT_ORIGIN = "http://localhost:8025";

export const DATABASE_NAME = "loadtest_vault";

export const DISPOSABLE_DATABASE_OPERATIONS = new Set([
  "test:loadtest-stack-create",
  "test:loadtest-stack",
  "test:loadtest-migration",
  "test:loadtest-scenario",
  "test:loadtest-session-pool",
  "test:loadtest-shared-vault-fixtures",
  "test:loadtest-shared-mutation-fixtures",
  "test:loadtest-teardown",
]);

export const LOADTEST_RESOURCE_PROFILE = "capped-local-v4";

export const LOADTEST_SERVICE_RESOURCE_LIMITS = Object.freeze({
  db: Object.freeze({ cpus: "1.0", memory: "256m" }),
  migrate: Object.freeze({ cpus: "1.0", memory: "256m" }),
  api: Object.freeze({ cpus: "1.0", memory: "256m" }),
  web: Object.freeze({ cpus: "1.0", memory: "256m" }),
  "retention-purge": Object.freeze({ cpus: "0.125", memory: "256m" }),
  mailpit: Object.freeze({ cpus: "0.25", memory: "256m" }),
});

export const MAX_CAPACITY_VUS = 100;

export const MAX_CAPACITY_SESSION_POOL_SIZE = 20;

export const BROWSER_HELPER_FAILURE_PHASES = new Set([
  "input_validation",
  "web_health_check",
  "browser_launch",
  "browser_context_creation",
  "browser_page_creation",
  "session_context_close",
  "mailpit_initial_clear",
  "sign_in_page_navigation",
  "email_form_fill",
  "email_form_hydration",
  "turnstile_ready",
  "magic_link_request_submit",
  "magic_link_request_response",
  "request_response_timeout",
  "request_not_dispatched",
  "request_unexpected_endpoint",
  "request_client_alert",
  "request_offline_client_alert",
  "request_client_status",
  "request_response_invalid_request",
  "request_response_turnstile_failed",
  "request_response_turnstile_unavailable",
  "request_response_rate_limit_unavailable",
  "request_response_rate_limited",
  "request_response_email_delivery_failed",
  "request_response_forbidden",
  "request_response_server_error",
  "request_response_rejected",
  "request_response_unexpected",
  "request_confirmation",
  "magic_link_email_wait",
  "magic_link_redemption",
  "personal_vault_setup",
  "personal_vault_creation",
  "personal_vault_unlock",
  "synthetic_account_creation",
  "session_read",
  "first_time_summary_missing",
  "first_time_browser_not_started",
  "first_time_sign_in_page_not_loaded",
  "first_time_sign_in_form_input_failed",
  "first_time_sign_in_form_blur_failed",
  "first_time_sign_in_form_not_hydrated",
  "first_time_email_typing_failed",
  "first_time_email_input_failed",
  "first_time_email_blur_failed",
  "first_time_email_validation_not_observed",
  "first_time_email_not_retained",
  "first_time_email_focus_failed",
  "first_time_email_focus_move_failed",
  "first_time_email_not_validated",
  "first_time_turnstile_not_ready",
  "first_time_passwordless_request_not_submitted",
  "first_time_passwordless_request_not_confirmed",
  "first_time_magic_link_mailpit_list_unavailable",
  "first_time_magic_link_mailpit_list_invalid",
  "first_time_magic_link_message_not_found",
  "first_time_magic_link_message_id_invalid",
  "first_time_magic_link_detail_unavailable",
  "first_time_magic_link_detail_invalid",
  "first_time_magic_link_link_missing",
  "first_time_magic_link_url_parse_failed",
  "first_time_magic_link_origin_mismatch",
  "first_time_magic_link_path_mismatch",
  "first_time_magic_link_token_missing",
  "first_time_magic_link_url_validation_incomplete",
  "first_time_magic_link_mailbox_cleanup_failed",
  "first_time_magic_link_not_captured",
  "first_time_magic_link_not_redeemed",
  "first_time_vault_name_not_filled",
  "first_time_custom_passphrase_not_selected",
  "first_time_custom_passphrase_not_filled",
  "first_time_custom_passphrase_form_state_invalid",
  "first_time_custom_passphrase_form_state_probe_incomplete",
  "first_time_passphrase_confirmation_not_filled",
  "first_time_setup_acknowledgement_not_checked",
  "first_time_vault_setup_submit_not_enabled",
  "first_time_vault_setup_submit_probe_not_started",
  "first_time_vault_setup_submit_button_missing",
  "first_time_vault_setup_submit_probe_incomplete",
  "first_time_vault_setup_submit_busy",
  "first_time_vault_setup_custom_mode_not_selected",
  "first_time_vault_setup_submit_disabled_unclassified",
  "first_time_vault_setup_not_submitted",
  "first_time_vault_initialization_client_crypto_failure",
  "first_time_vault_initialization_invalid_request",
  "first_time_vault_initialization_unauthenticated",
  "first_time_vault_initialization_forbidden",
  "first_time_vault_initialization_conflict",
  "first_time_vault_initialization_rate_limited",
  "first_time_vault_initialization_server_error",
  "first_time_vault_initialization_unexpected_response",
  "first_time_vault_initialization_transport_error",
  "first_time_vault_initialization_request_failure",
  "first_time_vault_initialization_post_failure",
  "first_time_vault_initialization_failure_unclassified",
  "first_time_vault_setup_validation_vault_name_invalid",
  "first_time_vault_setup_validation_passphrase_invalid",
  "first_time_vault_setup_validation_confirmation_invalid",
  "first_time_vault_setup_validation_acknowledgement_invalid",
  "first_time_vault_initialization_rejected",
  "first_time_vault_not_initialized",
  "first_time_vault_initialization_still_pending",
  "first_time_vault_setup_diagnostic_probe_incomplete",
  "first_time_vault_not_unlocked",
  "first_time_account_creation_link_not_visible",
  "first_time_account_creation_not_opened",
  "first_time_manual_uri_section_not_opened",
  "first_time_manual_uri_not_filled",
  "first_time_manual_uri_submit_not_enabled",
  "first_time_manual_uri_submit_not_clicked",
  "first_time_account_review_form_not_visible",
  "first_time_account_save_not_enabled",
  "first_time_account_not_created",
  "first_time_otp_not_rendered",
  "first_time_assertion_block_not_reached",
  "first_time_assertion_block_incomplete",
  "first_time_check_observations_missing",
  "first_time_assertions_failed",
  "rate_limit_summary_missing",
  "rate_limit_boundary_unsupported",
  "rate_limit_boundary_observations_missing",
  "rate_limit_boundary_attempt_count_mismatch",
  "rate_limit_boundary_admitted_count_mismatch",
  "rate_limit_boundary_limited_count_mismatch",
  "mailpit_final_clear",
  "browser_close",
  "helper_cancelled",
  "helper_timeout",
  "helper_output_limit",
  "helper_process_start",
  "helper_failed_unclassified",
  "helper_output_validation",
  "shared_web_health_check",
  "shared_browser_launch",
  "shared_mailpit_initial_clear",
  "shared_mutation_owner_session_preparation",
  "shared_mutation_vault_creation",
  "shared_mutation_context_close",
  "shared_owner_session_preparation",
  "shared_owner_vault_creation",
  "shared_member_session_preparation",
  "shared_invitation_creation",
  "shared_invitation_redemption",
  "shared_member_context_close",
  "shared_mailpit_final_clear",
  "shared_fixture_cleanup",
  "shared_fixture_output",
  "shared_management_navigation",
  "shared_creation_link",
  "shared_creation_form_fill",
  "shared_creation_submit",
  "shared_creation_response",
  "shared_creation_not_dispatched",
  "shared_creation_response_timeout",
  "shared_creation_validation_rejected",
  "shared_creation_unauthenticated",
  "shared_creation_forbidden",
  "shared_creation_conflict",
  "shared_creation_rate_limited",
  "shared_creation_server_error",
  "shared_creation_unexpected_status",
  "shared_creation_confirmation",
  "shared_creation_account_navigation",
  "shared_creation_account_form",
  "shared_creation_management_reload",
  "shared_creation_unlock_state",
  "shared_creation_unlock_state_timeout",
  "shared_creation_unlock_input",
  "shared_creation_unlock_hydration",
  "shared_creation_unlock_submit",
  "shared_creation_unlock_confirmation",
  "shared_creation_unlock_alert",
  "shared_creation_unlock_input_rejected",
  "shared_creation_unlock_alert_without_input",
  "shared_creation_unlock_workspace_omitted_vault",
  "shared_creation_unlock_membership_missing",
  "shared_creation_unlock_authentication_failure",
  "shared_creation_unlock_authorization_failure",
  "shared_creation_unlock_tabs_unavailable",
  "shared_creation_unlock_timeout",
  "shared_creation_unlock_authentication_failure",
  "shared_creation_unlock_cryptographic_failure",
  "shared_creation_unlock_passphrase_rejected",
  "shared_creation_unlock_sync_failure",
  "shared_creation_unlock_workspace_failure",
  "shared_creation_unlock_profile_failure",
  "shared_creation_unlock_identity_failure",
  "shared_creation_unlock_other_known_failure",
  "shared_creation_complete",
  "shared_invitation_tab",
  "shared_invitation_tab_unavailable",
  "shared_invitation_tablist_missing",
  "shared_invitation_tab_not_found",
  "shared_invitation_tab_hidden",
  "shared_invitation_tab_click",
  "shared_invitation_tab_click_failed",
  "shared_invitation_tab_disabled",
  "shared_invitation_form",
  "shared_invitation_input",
  "shared_invitation_submit",
  "shared_invitation_submit_request_observed",
  "shared_invitation_recipient_rejected",
  "shared_invitation_submit_button_missing",
  "shared_invitation_submit_button_hidden",
  "shared_invitation_submit_button_disabled",
  "shared_invitation_submit_multiple_buttons",
  "shared_invitation_submit_button_outside_viewport",
  "shared_invitation_submit_button_detached",
  "shared_invitation_submit_button_unstable",
  "shared_invitation_submit_click_intercepted",
  "shared_invitation_submit_click_timeout",
  "shared_invitation_submit_click_failed",
  "shared_invitation_response",
  "shared_invitation_response_timeout",
  "shared_invitation_not_dispatched",
  "shared_invitation_controls_form_mismatch",
  "shared_invitation_creation_error_alert",
  "shared_invitation_submit_still_pending",
  "shared_invitation_recipient_native_invalid",
  "shared_invitation_event_probe_unavailable",
  "shared_invitation_request_target_mismatch",
  "shared_invitation_submit_event_no_request",
  "shared_invitation_request_submit_not_observed",
  "shared_invitation_keyboard_event_not_observed",
  "shared_invitation_button_click_no_submit",
  "shared_invitation_enter_without_submit",
  "shared_invitation_activation_not_observed",
  "shared_invitation_validation_rejected",
  "shared_invitation_unauthenticated",
  "shared_invitation_forbidden",
  "shared_invitation_not_found",
  "shared_invitation_conflict",
  "shared_invitation_rate_limited",
  "shared_invitation_server_error",
  "shared_invitation_unexpected_status",
  "shared_invitation_confirmation",
  "shared_invitation_link_unavailable",
  "shared_invitation_link_invalid",
  "shared_invitation_complete",
]);

export const K6_VERSION = "0.57.0";

export const MAX_MIGRATION_STATS_SAMPLES = 600;

export const COMPOSE_FILES = [path.join(ROOT, "docker-compose.yml"), path.join(ROOT, "docker-compose.loadtest.yml")];

export const SCENARIOS = new Map([
  ["returning-personal", "personal-vault.js"],
  ["account-mutations", "account-mutations.js"],
  ["browser-smoke", "browser-smoke.js"],
  ["rate-limits", "rate-limits.js"],
  ["first-time", "browser-flows.js"],
  ["shared-vault", "shared-vault.js"],
  ["shared-account-mutations", "shared-account-mutations.js"],
]);

export const ALL_NON_CAPACITY_SCENARIO_CASES = Object.freeze(
  [...SCENARIOS.keys()]
    .filter((scenario) => scenario !== "capacity")
    .flatMap((scenario) =>
      scenario === "rate-limits"
        ? ["email", "network", "authenticated"].map((boundary) => Object.freeze({ scenario, boundary }))
        : [Object.freeze({ scenario })],
    ),
);

export const VALUE_OPTIONS = new Set([
  "project",
  "target",
  "confirm-migration",
  "confirm-target",
  "scenario",
  "boundary",
  "max-vus",
  "duration",
  "runner-placement",
]);

export const BOOLEAN_OPTIONS = new Set(["preserve-on-failure", "keep-stack"]);

export const SAFE_PROCESS_ENVIRONMENT = [
  "PATH",
  "HOME",
  "TMPDIR",
  "TMP",
  "TEMP",
  "LANG",
  "LC_ALL",
  "PLAYWRIGHT_BROWSERS_PATH",
  "XDG_CACHE_HOME",
  "XDG_RUNTIME_DIR",
  "LD_LIBRARY_PATH",
  "DYLD_LIBRARY_PATH",
  "DISPLAY",
  "WAYLAND_DISPLAY",
];
