export { redactSensitiveData } from "./application/redact-sensitive-data";
export { UnlockedVaultSession } from "./application/unlocked-vault-session";
export { decryptPayload, deserializeEncryptedEnvelope, deserializeKeyWrapEnvelope, encryptPayload, generateSymmetricKey, generateUserEncryptionKeyPair, serializeEncryptedEnvelope, serializeKeyWrapEnvelope, unwrapKeyForRecipient, wrapKeyForRecipient } from "./infrastructure/browser-crypto-envelope";
export type { EncryptedEnvelope, KeyWrapEnvelope } from "./infrastructure/browser-crypto-envelope";
export { initializePersonalVaultInBrowser } from "./infrastructure/browser-personal-vault-initializer";
export type { PersonalVaultInitializationMaterial } from "./infrastructure/browser-personal-vault-initializer";
export { unlockPersonalVault, unlockPersonalVaultWithUserRootKey } from "./infrastructure/browser-personal-vault-unlock";
export type { EncryptedPersonalVaultProfile } from "./infrastructure/browser-personal-vault-unlock";
export { changeVaultUnlockSecret, wrapUserRootKeyWithVaultUnlockSecret } from "./infrastructure/browser-vault-unlock-secret-change";
export { deriveVaultUnlockKey, validateVaultUnlockSecret } from "./infrastructure/browser-vault-unlock-key";
export { createUserEncryptionIdentity, recoverUserEncryptionPrivateKey } from "./infrastructure/browser-user-encryption-identity";
export { rotateUserEncryptionIdentity } from "./infrastructure/browser-user-encryption-key-rotation";
export { forgetRememberedBrowser, enrollRememberedBrowser, supportsLocalVerification, verifyRememberedBrowser } from "./infrastructure/browser-local-verification";
export { generateVaultUnlockSecret } from "./presentation/generate-vault-unlock-secret";
export { PasskeyRecoveryEnrollment } from "./presentation/passkey-recovery-enrollment";
export { PasskeyRecoveryReset } from "./presentation/passkey-recovery-reset";
export { loadEncryptedLocalVaultSnapshot, reconcileEncryptedLocalVaultSnapshot, removeAllEncryptedLocalVaultSnapshots, removeEncryptedLocalVaultSnapshot, saveEncryptedLocalVaultSnapshot } from "./infrastructure/browser-local-vault-snapshot";
export type { EncryptedLocalVaultSnapshot } from "./infrastructure/browser-local-vault-snapshot";
export { rotateVaultKey } from "./infrastructure/browser-vault-key-rotation";
export type { EncryptedVaultRotationInput, EncryptedVaultRotationResult } from "./infrastructure/browser-vault-key-rotation";
export { createEncryptedVaultExport, openEncryptedVaultExport } from "./infrastructure/browser-vault-export";
export { createPasskeyRecoveryPackage, passkeyRecoverySalt, recoverUserRootKeyFromPasskeyPackage } from "./infrastructure/browser-passkey-recovery-package";
export { authenticatePasskey, createPasskeyCredential, evaluatePasskeyPrf } from "./infrastructure/browser-passkey-prf";
export { recoverUserRootKeyWithPasskey } from "./infrastructure/browser-passkey-recovery-workflow";
