import { describe, expect, it, vi } from "vitest";
import {
  createPasswordlessAuthService,
  isMagicLinkToken,
  isSessionToken,
  normalizeEmail,
  PasswordlessChallengePersistenceError,
  PasswordlessEmailDeliveryError,
  type PasswordlessSession,
} from "@api/modules/identity/application/passwordless-authentication";

const token = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJK";
const sessionToken = `0123456789abcdef.${token}`;
const pwaHandoffId = ["pwa", "handoff", 123456].join("-");

function session(): PasswordlessSession {
  const now = new Date("2026-09-14T00:00:00.000Z");
  return {
    sessionId: "0123456789abcdef",
    accessToken: sessionToken,
    refreshToken: sessionToken,
    accessExpiresAt: new Date(now.getTime() + 900_000),
    refreshExpiresAt: new Date(now.getTime() + 2_592_000_000),
    principal: {
      issuer: "rhasia:passwordless",
      subject: "subject",
      email: "person@example.test",
      emailVerified: true,
      assurance: "active-session",
      sessionId: "0123456789abcdef",
    },
  };
}

describe("passwordless authentication application service", () => {
  it("normalizes email and accepts the credentials generated by the session factory", () => {
    expect(normalizeEmail(" Person@Example.Test ")).toBe("person@example.test");
    expect(isMagicLinkToken(token)).toBe(true);
    expect(isSessionToken(sessionToken)).toBe(true);
    expect(isSessionToken("0123456789abcdef" + token)).toBe(false);
  });

  it("creates a challenge and sends a link without exposing account existence", async () => {
    const repository = {
      createChallenge: vi.fn().mockResolvedValue(undefined),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const sender = { sendMagicLinkEmail: vi.fn().mockResolvedValue(undefined) };
    const buildActionUrl = vi.fn(
      () => new URL(`https://vault.example.test/auth/confirm#token=${token}&next=%2Fvaults`),
    );
    const service = createPasswordlessAuthService({
      repository,
      sender,
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1, 2, 3]) }),
      digestToken: () => new Uint8Array([4, 5, 6]),
      buildActionUrl,
      magicLinkTtlSeconds: 900,
      now: () => new Date("2026-09-14T00:00:00.000Z"),
    });

    await service.requestLink({ email: " Person@Example.Test ", client: "web", returnPath: "/vaults" });

    expect(buildActionUrl).toHaveBeenCalledWith("web", token, "/vaults");
    expect(repository.createChallenge).toHaveBeenCalledWith({
      tokenDigest: new Uint8Array([1, 2, 3]),
      challenge: { email: "person@example.test", client: "web", returnPath: "/vaults" },
      expiresAt: new Date("2026-09-14T00:15:00.000Z"),
    });
    expect(sender.sendMagicLinkEmail).toHaveBeenCalledWith({
      recipientEmail: "person@example.test",
      actionUrl: new URL(`https://vault.example.test/auth/confirm#token=${token}&next=%2Fvaults`),
    });
  });

  it("classifies challenge persistence and email delivery failures separately", async () => {
    const databaseError = Object.assign(new Error("database detail"), { code: "P1001" });
    const emailError = Object.assign(new Error("smtp detail"), { code: "EAUTH" });
    const repository = {
      createChallenge: vi.fn().mockRejectedValueOnce(databaseError).mockResolvedValue(undefined),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const sender = { sendMagicLinkEmail: vi.fn().mockRejectedValue(emailError) };
    const service = createPasswordlessAuthService({
      repository,
      sender,
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1, 2, 3]) }),
      digestToken: () => new Uint8Array([4, 5, 6]),
      buildActionUrl: () => new URL(`https://vault.example.test/auth/confirm#token=${token}`),
      magicLinkTtlSeconds: 900,
    });

    const challengeFailure = service.requestLink({
      email: "person@example.test",
      client: "web",
      returnPath: "/vaults",
    });
    await expect(challengeFailure).rejects.toBeInstanceOf(PasswordlessChallengePersistenceError);
    await expect(challengeFailure).rejects.toMatchObject({ cause: databaseError });
    expect(repository.createChallenge).toHaveBeenCalledOnce();

    const emailFailure = service.requestLink({
      email: "person@example.test",
      client: "web",
      returnPath: "/vaults",
    });
    await expect(emailFailure).rejects.toBeInstanceOf(PasswordlessEmailDeliveryError);
    await expect(emailFailure).rejects.toMatchObject({ cause: emailError });
    expect(sender.sendMagicLinkEmail).toHaveBeenCalledOnce();
  });

  it("builds a PWA-specific link with its transient handoff identifier", async () => {
    const repository = {
      createChallenge: vi.fn().mockResolvedValue(undefined),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const buildActionUrl = vi.fn(
      () =>
        new URL(`https://vault.example.test/auth/pwa-confirm#token=${token}&next=%2Fvaults&handoff=${pwaHandoffId}`),
    );
    const service = createPasswordlessAuthService({
      repository,
      sender: { sendMagicLinkEmail: vi.fn().mockResolvedValue(undefined) },
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1, 2, 3]) }),
      digestToken: () => new Uint8Array([4, 5, 6]),
      buildActionUrl,
      magicLinkTtlSeconds: 900,
      now: () => new Date("2026-09-14T00:00:00.000Z"),
    });

    await service.requestLink({
      email: "person@example.test",
      client: "pwa",
      returnPath: "/vaults",
      handoffId: pwaHandoffId,
      handoffVerifier: "v".repeat(43),
    });

    expect(buildActionUrl).toHaveBeenCalledWith("pwa", token, "/vaults", pwaHandoffId);
    expect(repository.createChallenge).toHaveBeenCalledWith(
      expect.objectContaining({
        pwaHandoff: {
          handoffIdDigest: new Uint8Array([4, 5, 6]),
          verifierDigest: new Uint8Array([4, 5, 6]),
          expiresAt: new Date("2026-09-14T00:15:00.000Z"),
        },
      }),
    );
    expect(repository.createChallenge).toHaveBeenCalledWith(
      expect.objectContaining({ challenge: { email: "person@example.test", client: "pwa", returnPath: "/vaults" } }),
    );
  });

  it("rotates and publishes a PWA callback session without exposing it to the client", async () => {
    const repository = {
      createChallenge: vi.fn(),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn().mockResolvedValue(true),
      redeemPwaHandoff: vi.fn(),
    };
    const digestToken = vi.fn(() => new Uint8Array([9]));
    const service = createPasswordlessAuthService({
      repository,
      sender: { sendMagicLinkEmail: vi.fn() },
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1]) }),
      digestToken,
      buildActionUrl: () => new URL("https://vault.example.test/auth/pwa-confirm"),
      magicLinkTtlSeconds: 900,
      now: () => new Date("2026-09-14T00:00:00.000Z"),
    });

    await service.publishPwaHandoff(sessionToken, pwaHandoffId);

    expect(repository.publishPwaHandoff).toHaveBeenCalledWith(
      new Uint8Array([9]),
      "0123456789abcdef",
      new Uint8Array([9]),
      new Date("2026-09-14T00:00:00.000Z"),
    );
    expect(digestToken).toHaveBeenCalledTimes(2);
  });

  it("rejects a PWA link request without a safe handoff verifier", async () => {
    const repository = {
      createChallenge: vi.fn(),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const service = createPasswordlessAuthService({
      repository,
      sender: { sendMagicLinkEmail: vi.fn() },
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1]) }),
      digestToken: () => new Uint8Array([9]),
      buildActionUrl: () => new URL("https://vault.example.test/auth/pwa-confirm"),
      magicLinkTtlSeconds: 900,
    });

    await expect(
      service.requestLink({ email: "person@example.test", client: "pwa", returnPath: "/vaults" }),
    ).rejects.toThrow("PWA authentication handoff is invalid.");
    expect(repository.createChallenge).not.toHaveBeenCalled();
  });

  it("atomically consumes a valid challenge, provisions the account, and creates a session", async () => {
    const createdSession = session();
    const repository = {
      createChallenge: vi.fn(),
      consumeChallenge: vi.fn().mockResolvedValue({
        email: "person@example.test",
        client: "mobile",
        returnPath: "/vaults",
      }),
      findOrCreateAccount: vi.fn().mockResolvedValue({
        applicationUserId: "user-id",
        issuer: "rhasia:passwordless",
        subject: "subject",
        email: "person@example.test",
      }),
      createSession: vi.fn().mockResolvedValue(createdSession),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn(),
      revokeSession: vi.fn(),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const service = createPasswordlessAuthService({
      repository,
      sender: { sendMagicLinkEmail: vi.fn() },
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1]) }),
      digestToken: vi.fn(() => new Uint8Array([9])),
      buildActionUrl: () => new URL("https://vault.example.test/auth/mobile"),
      magicLinkTtlSeconds: 900,
    });

    await expect(service.redeem(token, "mobile")).resolves.toEqual({ session: createdSession, returnPath: "/vaults" });
    expect(repository.consumeChallenge).toHaveBeenCalledWith(new Uint8Array([9]), "mobile", expect.any(Date));
    expect(repository.findOrCreateAccount).toHaveBeenCalledWith("person@example.test", expect.any(Date));
    expect(repository.createSession).toHaveBeenCalledWith(
      expect.objectContaining({ applicationUserId: "user-id" }),
      expect.any(Date),
    );
  });

  it("rejects malformed credentials before touching persistence and delegates refresh validation", async () => {
    const repository = {
      createChallenge: vi.fn(),
      consumeChallenge: vi.fn(),
      findOrCreateAccount: vi.fn(),
      createSession: vi.fn(),
      verifyAccessToken: vi.fn(),
      verifyBrowserSession: vi.fn(),
      rotateRefreshToken: vi.fn().mockResolvedValue(null),
      revokeSession: vi.fn().mockResolvedValue(undefined),
      publishPwaHandoff: vi.fn(),
      redeemPwaHandoff: vi.fn(),
    };
    const service = createPasswordlessAuthService({
      repository,
      sender: { sendMagicLinkEmail: vi.fn() },
      generateToken: () => ({ rawToken: token, digest: new Uint8Array([1]) }),
      digestToken: vi.fn(() => new Uint8Array([9])),
      buildActionUrl: () => new URL("https://vault.example.test/auth/confirm"),
      magicLinkTtlSeconds: 900,
    });

    await expect(service.redeem("malformed", "web")).resolves.toBeNull();
    await expect(service.refresh(`${"0123456789abcdef"}.${token}`)).resolves.toBeNull();
    expect(repository.consumeChallenge).not.toHaveBeenCalled();
    expect(repository.rotateRefreshToken).toHaveBeenCalledWith(
      new Uint8Array([9]),
      "0123456789abcdef",
      expect.any(Date),
    );
    expect(repository.revokeSession).not.toHaveBeenCalled();
  });
});
